### PR TITLE
Feature/settings screen

### LINKED ISSUE #23: Notifications

### PR DESCRIPTION
**Pull request by KiOui**
Closes #23 

Added FireBase messaging. The App will now automatically register devices for push notifications. Changes to the settings screen so that users can change their notification preferences.

I have not added push notification routing yet, there are TODO's for that in the code. We need to port deepLinking.js from the old app if we want routing.

How to test:
1. Check the settings screen for the available notification settings.
2. Check the code for the setup of FireBaseMessaging

### CODE REVIEW

**Comment by KiOui** [comment]
@DeD1rk I have tried to merge the code as best as I could, events are in a constantly loading state now (I don't know if this is also the case on master).

**Comment by DeD1rk** [comment]
Dont worry, thats because of an api change to registrations that will be solved in the admin screens PR

**Comment by KiOui** [comment]
Ahh nice

**Comment by KiOui** [comment]
I see that I also screwed up the signing of the iOS app, did you make any changes to the Info plist via Xcode?

**Comment by DeD1rk** [comment]
There were some changes in the fastlane PR, but I think its probably something with notifications and background permissions.

**Comment by DeD1rk** [comment]
Okay I think the changes to project.pbxproj are breaking the signing. Some changes there are necessary of course for the pushnotifications background permissions, but I have no idea exactly which lines those are. Sadly xcode's files are very incompatible with source control, so I think it would probably be best if you reset those files to what is now on master, and re-apply the necessary changes from xcode.

**Comment by KiOui** [comment]
> Okay I think the changes to project.pbxproj are breaking the signing. Some changes there are necessary of course for the pushnotifications background permissions, but I have no idea exactly which lines those are. Sadly xcode's files are very incompatible with source control, so I think it would probably be best if you reset those files to what is now on master, and re-apply the necessary changes from xcode.

Okay let's try that, my signing now does not work anymore (on my local machine) but it might on GH actions

**Comment by DeD1rk** [comment]
Perfect, I'll do some refactoring, fill in the TODO's and merge

**Comment by KiOui** [comment]
Heujj

**Comment by KiOui** [comment]
"Some refactoring" == 400 changes haha

**Pull request merged**
