### PR TITLE
Made commitee and society groups display in alphabetical order

### LINKED ISSUE #350: Thaliapp: Groups are sorted in reverse alphabetical order
The committees and societies are displayed in reverse order. (Boards are displayed correctly)

### PR DESCRIPTION
**Pull request by JeeVee11**
Closes #350 .

### Summary
Made committee and society groups display in alphabetical order

### How to test
Steps to test the changes you made:
1. Go to 'GROUPS'.
2. Click on committees or societies.
3. See that it is in alphabetical order.
4. Boards are still from newest to oldest.

### CODE REVIEW

**Comment by JAicewizard** [comment]
@DeD1rk Do you now why this happens for only non-board groups? It kind of sounds like this should (also) be addressed in concrexit. In that case it might be better to sort based on name instead of reverse them

**Comment by JAicewizard** [comment]
@DeD1rk Do you now why this happens for only non-board groups? It kind of sounds like this should (also) be addressed in concrexit. In that case it might be better to sort based on name instead of reverse them

**Review by DeD1rk — APPROVED** [review]
Seems good like this! let's test the testflight to be sure though

**Comment by DeD1rk** [comment]
Apart from the visual bug, search doesnt filter partner events: image and if i search for an emptystring and pull to refresh, I get this incorrect result: image

**Pull request merged**
