### PR TITLE
Fix previously filtered events not showing on the calendar

### LINKED ISSUE #468: Study trip not in calendar
### Describe the bug
When scrolling down in the calendar the study trip does not show up. It is there when using the search function.

### PR DESCRIPTION
**Pull request by JAicewizard**
Closes #468.

### Summary
Previously, a mistake in interpreting the dart syntax led to previous events being cleared before using them.

### How to test
Steps to test the changes you made:
1. Go to calendar
2. Scroll down to the bottom
3. See study trip

### CODE REVIEW

**Comment by DeD1rk** [comment]
Wait so what syntqx was wrong? Does the ... = x + y == z do ... = x + 1?

**Comment by JAicewizard** [comment]
The syntax issue is with `..clear()`. Since it returns the object after clearing the List. The rest is just making it a bit cleaner

**Comment by DeD1rk** [comment]
Ah that explains it yeah, good find

**Comment by DeD1rk** [comment]
Maybe a test would be good?

**Review by DeD1rk — DISMISSED** [review]

**Comment by JAicewizard** [comment]
Implemented the test, based on a new PR #472

**Review by Scarletto — APPROVED** [review]
بەلامەوە باش دەردەکەوێت

**Pull request merged**
